spring.application.name=user-registry-spring

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Plbsopalex11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
