spring.application.name=user-registry-spring

spring.datasource.url=jbdc:mysql://localhost:3306/databasname
spring.datasource.username=root
spring.datasource.password=Plbsopalex11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
